directories:
  output: release
  buildResources: build
appId: com.example.timetable
productName: Timetable
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target: nsis
  icon: build/icon.png
mac:
  target: dmg
  icon: build/icon.png
linux:
  target:
    - AppImage
    - deb
  icon: build/icon.png
electronVersion: 39.2.7
